#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/home/rocha/opt/gwt-linux-1.5.3/gwt-user.jar:/home/rocha/opt/gwt-linux-1.5.3/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" opensoaring.OpenSoaring/OpenSoaring.html;
